version: "3.8"
services:
  flask_app: 
    build:   
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005" 
    volumes:
      - .:/efi_flask
    env_file:
      - .env
    depends_on:
      - mysql_db
    container_name: flask_app

  mysql_db:
    image: mysql:5.7  # Use the official MySQL 5.7 image from Docker Hub
    env_file:
        - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}  # Create a database named 'mydatabase'
      MYSQL_USER: ${MYSQL_USER}  # Create a MySQL user 'myuser'
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  # Set the password for 'myuser'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Set the root password for MySQL
    ports:
      - "3308:3306"  # Map host port 3307 to container port 3306 for MySQL
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    container_name: mysqldatabase

volumes:
  db_data: